Throw error if none of the db rows are affected
SeaQL/sea-orm pull request #211
Opened 2021-09-28 11:01 UTC by billy1624

Resolve #181

2021-09-30 03:42 UTC, tyt2y3 commented
We need unit tests using the mock connection on this behaviour too

2021-09-30 04:55 UTC, billy1624 commented
> We need unit tests using the mock connection on this behaviour too

Added!

2021-09-30 11:13 UTC, tyt2y3 commented on src/executor/update.rs
> +            .append_query_results(vec![
I guess this is not needed. Let me try.

2021-09-30 15:47 UTC, tyt2y3 requested changes
I have noticed a problem. this behavior should only applies to update_one, while for update many, it's fine to have updated 0 rows.

2021-10-04 03:48 UTC, billy1624 commented
> I have noticed a problem. this behavior should only applies to update_one, while for update many, it's fine to have updated 0 rows.

Fixed

2021-10-05 13:59 UTC, tyt2y3 approved these changes

2021-10-05 14:01 UTC, merged