Dump SeaORM Dependency from SeaSchema's Migrator
SeaQL/sea-orm pull request #666
Opened 2022-04-08 05:19 UTC by billy1624

## PR Info

- Closes SeaQL/sea-schema#57
- Dependencies:
  - SeaQL/sea-schema#59

## Adds

## Fixes

## Breaking Changes

## Changes

2022-04-09 13:58 UTC, tyt2y3 commented
This changeset is too big and it kind of broke the API for no good reason. Is there another approach?

2022-04-09 16:37 UTC, billy1624 commented
What you mean by "breaking the API"?

2022-04-20 06:41 UTC, billy1624 commented
Hey @tyt2y3, this is ready for review!

2022-04-30 12:47 UTC, tyt2y3 commented on examples/graphql_example/migration/src/lib.rs
> +pub use entity::sea_orm::migration::prelude::*;
why is this `entity::sea_orm` instead of `sea_orm`?

2022-04-30 12:53 UTC, tyt2y3 commented on Cargo.toml
> +    "migration",
I don't think we should add this as default feature

2022-04-30 12:53 UTC, tyt2y3 commented on Cargo.toml
> +migration = ["sea-schema", "macros", "clap", "tracing-subscriber", "dotenv", "async-std"]
It seems that what we need is one more crate sea-orm-migration

2022-04-30 13:00 UTC, tyt2y3 requested changes

2022-04-30 13:00 UTC, tyt2y3 commented on Cargo.toml
> +clap = { version = "^2.33", optional = true }
These dependencies definitely do not belong here :(

2022-04-30 13:17 UTC, tyt2y3 commented on examples/graphql_example/migration/src/lib.rs
> +pub use entity::sea_orm::migration::prelude::*;
we should make it `sea_orm_cli::migration` or `sea_orm_migration`

2022-04-30 13:18 UTC, tyt2y3 commented on examples/graphql_example/migration/src/lib.rs
> +pub use entity::sea_orm::migration::prelude::*;
`entity` is a pure logic crate it does not make sense for `migration` be imported via `entity`

2022-04-30 13:19 UTC, tyt2y3 commented on Cargo.toml
> +    "migration",
actually we should remove this from the main `sea-orm` crate altogether

2022-04-30 13:25 UTC, tyt2y3 commented
Architecturally, the dependency chain should be `sea-query` (AST) -> `sea-schema` (logic) -> `sea-orm-xxx` (API) -> `sea-orm-cli` (executable)

2022-04-30 13:38 UTC, tyt2y3 commented
Let's take the time to make it right once and for all

2022-05-03 14:15 UTC, tyt2y3 commented
> I would refer splitting it into `sea-orm-migration`, as I don't want `sea-orm-cli` depends on `sea-orm`. It'll makes things complicated.

Agree

2022-05-09 10:54 UTC, tyt2y3 approved these changes

2022-05-09 11:48 UTC, merged

2022-05-09 11:48 UTC, tyt2y3 commented
Hell yeah