Drop `SelectTwoMany::one()` method
SeaQL/sea-orm pull request #813
Opened 2022-06-22 09:45 UTC by billy1624

## PR Info

- Closes https://github.com/SeaQL/sea-orm/issues/486

## Breaking Changes

- [ ] Drop `SelectTwoMany::one()` method: `SelectTwoMany` is for selecting models of a one-to-many relationship but `SelectTwoMany::one()` returns `Option<(E, Option<F>)>` and the return value is a pair of models instead of `(E, Vec<F>)` which is weird select result for a one-to-many relationship

2022-06-23 17:11 UTC, tyt2y3 commented
I guess we would like to add some API docs somewhere explaining the absence of such function.
But yeah it's a trap

2022-06-26 10:27 UTC, tyt2y3 requested changes
Documentation

2022-06-27 16:39 UTC, tyt2y3 commented
Actually, it might be "easy" to make two queries, first `one()`, and then `find_related` ?

2022-06-28 03:20 UTC, billy1624 commented
Docs updated :)

2022-07-10 15:41 UTC, merged